export interface Payment {
  id: string;
  name: string;
  domain: string;
  email: string;
  planType: "Growth" | "Enterprise" | "Starter";
  amount: string;
  status: "Paid" | "Pending" | "Failed";
  createdAt: string;
  avatarColor: string;
}

export const AllPaymentsData: Payment[] = [
  {
    id: "1",
    name: "Acme Corp",
    domain: "domain@e2e.com",
    email: "acmecorp@gmail.com",
    planType: "Growth",
    amount: "$67",
    status: "Paid",
    createdAt: "April 14, 2020",
    avatarColor: "bg-purple-100 text-purple-600",
  },
  {
    id: "2",
    name: "Betopia Group",
    domain: "betopiagroup@e2e.com",
    email: "betopiagroup@gmail.com",
    planType: "Enterprise",
    amount: "$67",
    status: "Paid",
    createdAt: "April 14, 2020",
    avatarColor: "bg-purple-100 text-purple-600",
  },
  {
    id: "3",
    name: "Gamma Ltd",
    domain: "domain@e2e.com",
    email: "acmecorp@gmail.com",
    planType: "Starter",
    amount: "$67",
    status: "Paid",
    createdAt: "April 14, 2020",
    avatarColor: "bg-purple-100 text-purple-600",
  },
  {
    id: "4",
    name: "Gamma Ltd",
    domain: "domain@e2e.com",
    email: "acmecorp@gmail.com",
    planType: "Starter",
    amount: "$67",
    status: "Paid",
    createdAt: "April 14, 2020",
    avatarColor: "bg-purple-100 text-purple-600",
  }, {
    id: "1",
    name: "Acme Corp",
    domain: "domain@e2e.com",
    email: "acmecorp@gmail.com",
    planType: "Growth",
    amount: "$67",
    status: "Paid",
    createdAt: "April 14, 2020",
    avatarColor: "bg-purple-100 text-purple-600",
  },
  {
    id: "2",
    name: "Betopia Group",
    domain: "betopiagroup@e2e.com",
    email: "betopiagroup@gmail.com",
    planType: "Enterprise",
    amount: "$67",
    status: "Paid",
    createdAt: "April 14, 2020",
    avatarColor: "bg-purple-100 text-purple-600",
  },
  {
    id: "3",
    name: "Gamma Ltd",
    domain: "domain@e2e.com",
    email: "acmecorp@gmail.com",
    planType: "Starter",
    amount: "$67",
    status: "Paid",
    createdAt: "April 14, 2020",
    avatarColor: "bg-purple-100 text-purple-600",
  },
  {
    id: "4",
    name: "Gamma Ltd",
    domain: "domain@e2e.com",
    email: "acmecorp@gmail.com",
    planType: "Starter",
    amount: "$67",
    status: "Paid",
    createdAt: "April 14, 2020",
    avatarColor: "bg-purple-100 text-purple-600",
  }, {
    id: "1",
    name: "Acme Corp",
    domain: "domain@e2e.com",
    email: "acmecorp@gmail.com",
    planType: "Growth",
    amount: "$67",
    status: "Paid",
    createdAt: "April 14, 2020",
    avatarColor: "bg-purple-100 text-purple-600",
  },
  {
    id: "2",
    name: "Betopia Group",
    domain: "betopiagroup@e2e.com",
    email: "betopiagroup@gmail.com",
    planType: "Enterprise",
    amount: "$67",
    status: "Paid",
    createdAt: "April 14, 2020",
    avatarColor: "bg-purple-100 text-purple-600",
  },
  {
    id: "3",
    name: "Gamma Ltd",
    domain: "domain@e2e.com",
    email: "acmecorp@gmail.com",
    planType: "Starter",
    amount: "$67",
    status: "Paid",
    createdAt: "April 14, 2020",
    avatarColor: "bg-purple-100 text-purple-600",
  },
  {
    id: "4",
    name: "Gamma Ltd",
    domain: "domain@e2e.com",
    email: "acmecorp@gmail.com",
    planType: "Starter",
    amount: "$67",
    status: "Paid",
    createdAt: "April 14, 2020",
    avatarColor: "bg-purple-100 text-purple-600",
  },
];